Src/apps/blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import BlogDetailView
from .views import BlogListView
from .views import TagListView
from .views import ArchiveView
from .views import BlogListByCategoryView

urlpatterns = [url(r"^tag/(?P<tag_name>[\w,-]+)$", BlogListView.as_view(), name="tag"),
               url(r"^category/(?P<pk>\d+)/(?P<cat_name>\w+)$", BlogListByCategoryView.as_view(), name="category"),
               url(r"^tags$", TagListView.as_view(), name="tag_list"),
               url(r"^archives", ArchiveView.as_view(), name="archives"),
               url(r"^$", BlogListView.as_view(), name="home"),
               url(r"^(?P<pk>\d+)/(?P<blog_link>[\w,-]+)$", BlogDetailView.as_view(), name="blog_detail"),

               ]

Src/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from apps.blog.views import AboutView
from apps.blog.views import BlogListView
from apps.blog.views import LatestPosts
from django_blog.sitemaps import BlogSitemap, IndexSitemap

admin.autodiscover()

sitemaps = {
    'index': IndexSitemap,
    'blog': BlogSitemap,

}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', BlogListView.as_view(), name="home"),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^about$', AboutView.as_view(), name='about'),
    url(r'^404', TemplateView.as_view(template_name="404.html")),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    url(r'^humans.txt$', TemplateView.as_view(template_name="humans.txt", content_type="text/plain")),
    url(r'^rss/', LatestPosts(), name='feeds'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

Src/templates/base.html
{% load staticfiles %}
{% load compress %}
<!doctype html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block head_title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body {
        padding-top: 50px;
        padding-bottom: 20px;
        }
    </style>
    <!--<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>


    {% block head_css %}{% endblock %}
    {% block head_javascript %}{% endblock %}
</head>
<body>
<!--[if lt IE 8]>
<p class="browserupgrade">你使用的游览器太落后啦, <a href="http://browsehappy.com/">升级你的游览器获取更好地阅读体验</a></p>
<![endif]-->

{% block navbar %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Dennis</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <form class="navbar-form navbar-right" role="form">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="python" id="search-text">
                </div>
                <button type="button" class="btn btn-default" id="btn-search">搜索</button>
            </form>
            <ul class="nav navbar-nav">
                <li {% if tag_active %}class="active" {% endif %}><a href="{% url 'blog:tag_list' %}">标签</a></li>
                <li {% if tag_active %}class="active" {% endif %}><a href="{% url 'blog:archives' %}">归档</a></li>
                <li {% if about_active %}class="active" {% endif %}><a href="{% url 'about' %}">关于</a></li>
                {% if user.is_authenticated %}
                <li ><a href="{% url 'admin:index' %}">管理</a></li>
                {% endif %}
            </ul>
        </div><!--/.navbar-collapse -->
    </div>
</nav>

{% endblock %}
<div class="wrapper">

    <div class="container">
        <div class="row body">
            <div class="col-md-8 content">

                {% block content %}{% endblock %}
            </div>

            <div class="col-md-4">

                <!-- Latest Posts -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>最近文章</h4>
                    </div>
                    <ul class="list-group">
                        {% for blog in recent_blogs %}
                        <li class="list-group-item"><a href="{{blog.get_absolute_url}}">{{blog.title}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>


                <!-- Categories -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>文章分类</h4>
                    </div>
                    <ul class="list-group">
                        {% for category in categories %}
                        <li class="list-group-item"><a
                                href="{%url 'blog:category' category.id category.title%}">{{category.title}}</a></li>
                        {% endfor %}
                    </ul>
                </div>


                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>友情链接</h4>
                    </div>
                    <ul class="list-group">
                        {% for friend in friends %}
                        <li class="list-group-item"><a href="{{friend.url}}">{{friend.title}}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>图书推荐</h4>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><a href="https://book.douban.com/subject/23008813/">高性能MySQL第三版</a>
                        <li class="list-group-item"><a href="https://book.douban.com/subject/3117898/">Python源码剖析</a>
                        <li class="list-group-item"><a href="https://read.douban.com/ebook/7519526/">Redis设计与实现</a>
                        <li class="list-group-item"><a href="https://book.douban.com/subject/6021440/">黑客与画家</a>

                        </li>
                    </ul>
                </div>
                <!--<img src="{% static 'img/text.png' %}" class="img-responsive">-->
            </div>

        </div>
    </div>
</div>

<footer>
    <div class="container">
        <hr/>
        <p class="text-center">Copyright <a href="http://foofish.net">foofish</a> &copy; 2015. All rights reserved.
            Powere by<a href="https://github.com/lzjun567/django_blog"> Django_Blog</a> & <a
                    href="https://www.digitalocean.com/?refcode=af4cff8f42bc" target="_blank">DigitalOcean</a></p>
    </div>
</footer>

</div>

<script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
<script>window.jQuery || document.write('<script src="static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
<script>

        $("#btn-search").click(function(){

        var keyword = $("#search-text").val();
        if (keyword == ""){
            keyword = "python";
        }
        location.href = "https://www.google.com/search?q=site:foofish.net %20"+keyword;

        });



</script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '{{ga_id}}', 'auto');
  ga('send', 'pageview');



</script>
{% block footer_javascript %}{% endblock %}
</body>
</html>