Src/apps/blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from .views import BlogDetailView
from .views import BlogListView
from .views import TagListView
from .views import ArchiveView
from .views import BlogListByCategoryView

urlpatterns = [url(r"^tag/(?P<tag_name>[\w,-]+)$", BlogListView.as_view(), name="tag"),
               url(r"^category/(?P<pk>\d+)/(?P<cat_name>\w+)$", BlogListByCategoryView.as_view(), name="category"),
               url(r"^tags$", TagListView.as_view(), name="tag_list"),
               url(r"^archives", ArchiveView.as_view(), name="archives"),
               url(r"^$", BlogListView.as_view(), name="home"),
               url(r"^(?P<pk>\d+)/(?P<blog_link>[\w,-]+)$", BlogDetailView.as_view(), name="blog_detail"),

               ]

Src/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from apps.blog.views import AboutView
from apps.blog.views import BlogListView
from apps.blog.views import LatestPosts
from django_blog.sitemaps import BlogSitemap, IndexSitemap

admin.autodiscover()

sitemaps = {
    'index': IndexSitemap,
    'blog': BlogSitemap,

}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', BlogListView.as_view(), name="home"),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^about$', AboutView.as_view(), name='about'),
    url(r'^404', TemplateView.as_view(template_name="404.html")),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    url(r'^humans.txt$', TemplateView.as_view(template_name="humans.txt", content_type="text/plain")),
    url(r'^rss/', LatestPosts(), name='feeds'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

Src/apps/blog/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import re

from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core import urlresolvers
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify


class Blog(models.Model):
    STATUS_CHOICES = (
        ('d', "草稿"),
        ('p', "已发布"),
    )

    title = models.CharField('标题', max_length=150, db_index=True, unique=True)
    link = models.CharField('链接', max_length=150, default='')
    link.help_text = "Cool URIs don't change"
    cover = models.URLField('封面', default='', blank=True)
    snippet = models.CharField('摘要', max_length=500, default='')
    content = models.TextField('内容', )

    add_time = models.DateTimeField('创建时间', auto_now_add=True)
    publish_time = models.DateTimeField('发表时间', null=True)
    update_time = models.DateTimeField('修改时间')
    status = models.CharField('状态', max_length=1, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0])

    is_public = models.BooleanField('公开', default=True)
    is_top = models.BooleanField('置顶', default=False)
    access_count = models.IntegerField('浏览量', default=1, editable=False)
    category = models.ForeignKey('Category', verbose_name='所属分类')
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', null=True, blank=True)
    tags.help_text = '标签'
    author = models.ForeignKey(User, verbose_name='作者')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'

    def save(self, *args, **kwargs):
        self.link = slugify(self.link)
        self.snippet = self.snippet or self.content[:140]
        modified = kwargs.pop("modified", True)
        if modified:
            self.update_time = datetime.datetime.utcnow()
        super(Blog, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=(self.id, self.link))

    def __str__(self):
        return self.title

    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return urlresolvers.reverse("admin:%s_%s_change" % (content_type.app_label, content_type.model),
                                    args=(self.id,))


class Category(models.Model):
    """
    大分类
    """
    title = models.CharField('名称', max_length=50, db_index=True, unique=True)

    class Meta:
        ordering = ['title', ]
        verbose_name = '文章分类'
        verbose_name_plural = '文章分类'

    def __str__(self):
        return self.title


class Tag(models.Model):
    """
    小标签
    """
    title = models.CharField('名称', max_length=50, db_index=True, unique=True)

    def save(self, *args, **kwargs):
        self.title = re.sub("\s", "", self.title)
        super(Tag, self).save(*args, **kwargs)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'

    def __str__(self):
        return self.title


class Friend(models.Model):
    """
    友情链接
    """
    title = models.CharField('名称', max_length=100, default='')
    url = models.URLField('链接', default='')
    position = models.SmallIntegerField('位置', default=1)
    active = models.BooleanField('激活', default=True)

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = '友情链接'

    def __str__(self):
        return self.title

Src/apps/blog/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import datetime
from django.forms import ModelForm
from django.forms import CharField
from django.forms import Textarea


from pagedown.widgets import AdminPagedownWidget


class BlogForm(ModelForm):
    content = CharField(label='内容', widget=AdminPagedownWidget())
    snippet = CharField(label='摘要',
                        widget=Textarea(attrs={'cols': 85, 'rows': 7}),
                        required=False)


    def save(self, commit=True):
        instance = super(BlogForm, self).save(commit=False)
        if instance.status == 'p' and instance.publish_time is None:
            instance.publish_time = datetime.datetime.now()
        if commit:
            instance.save()
        return instance

Src/apps/blog/views.py
# -*- coding: utf-8 -*-

import random

from django.conf import settings
from django.contrib.syndication.views import Feed
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .libs.tag_cloud import TagCloud
from .models import Blog, Tag

__author__ = "liuzhijun"


class AboutView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context['about_active'] = True
        return context


class TagListView(ListView):
    template_name = 'tag_list.html'
    context_object_name = 'tag_list'
    model = Tag

    def get_context_data(self, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        tag_list = context.get("tag_list")
        # 有博文的tag
        tag_list_have_blog = []
        for tag in tag_list:
            blog_count = Blog.objects.filter(tags__pk=tag.id).count()
            if blog_count > 0:
                tag.blog_count = blog_count
                tag_list_have_blog.append(tag)

        max_count = min_count = 0
        if len(tag_list_have_blog) > 0:
            max_count = max(tag_list_have_blog, key=lambda tag: tag.blog_count).blog_count
            min_count = min(tag_list_have_blog, key=lambda tag: tag.blog_count).blog_count

        tag_cloud = TagCloud(min_count, max_count)

        for tag in tag_list_have_blog:
            tag_font_size = tag_cloud.get_tag_font_size(tag.blog_count)
            color = tag_cloud.get_tag_color(tag.blog_count)
            tag.color = color
            tag.font_size = tag_font_size

        context['tag_list'] = tag_list_have_blog
        context['tag_active'] = True
        return context


class ArchiveView(ListView):
    template_name = "archive.html"
    context_object_name = "blog_list"

    def get_queryset(self):
        return Blog.objects.filter(status='p', is_public=True).order_by('-publish_time')


class BlogListView(ListView):
    template_name = 'post_list.html'
    paginate_by = settings.PAGE_SIZE
    context_object_name = "blog_list"

    def get_queryset(self):
        # 只显示状态为发布且公开的文章列表
        query_condition = {
            'status': 'p',
            'is_public': True
        }

        if 'tag_name' in self.kwargs:
            query_condition['tags__title'] = self.kwargs['tag_name']
        elif 'cat_name' in self.kwargs:
            query_condition['category__title'] = self.kwargs['cat_name']

        return Blog.objects.filter(**query_condition).order_by('-publish_time')

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        tag_name = self.kwargs.get('tag_name')
        if tag_name:
            context['tag_title'] = tag_name
            context['tag_id'] = 1

            context['tag_description'] = ''
        else:
            context['index_active'] = True

        # 最近文章
        return context


class BlogListByCategoryView(ListView):
    template_name = 'post_list.html'
    paginate_by = settings.PAGE_SIZE
    context_object_name = "blog_list"

    def get_queryset(self):
        # 只显示状态为发布且公开的文章列表
        query_condition = dict({'status': 'p', 'is_public': True})
        query_condition['category__id'] = self.kwargs['pk']
        return Blog.objects.filter(**query_condition).order_by('-publish_time')

    def get_context_data(self, **kwargs):
        context = super(BlogListByCategoryView, self).get_context_data(**kwargs)
        tag_name = self.kwargs.get('tag_name')
        if tag_name:
            context['tag_title'] = tag_name

            context['tag_description'] = ''
        else:
            context['index_active'] = True

        # 最近文章
        return context


class BlogDetailView(DetailView):
    """
    文章详情
    """
    model = Blog
    template_name = "post_detail.html"

    def get_object(self, queryset=None):
        blog = super(BlogDetailView, self).get_object(queryset)
        if blog.link != self.kwargs['blog_link']:
            raise Http404()

        if blog.status == 'd' or (not blog.is_public and self.request.user != blog.author):
            raise PermissionDenied
        # 阅读数增1
        blog.access_count += 1
        blog.save(modified=False)
        return blog

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        current_post = context.get("object")

        # 随机文章
        count = Blog.objects.filter(status='p', is_public=True).count()
        range_count = 5
        if count < range_count:
            range_count = count

        randint = random.randint(0, count - range_count)
        try:
            random_posts = Blog.objects.exclude(pk=current_post.id).filter(status='p', is_public=True)[
                           randint:randint + range_count]
        except IndexError:
            random_posts = None
        context['random_posts'] = random_posts
        return context


class LatestPosts(Feed):
    """
    RSS 输出
    """
    title = "foofish 的笔录"
    link = "/"

    def items(self):
        blogs = Blog.objects.filter(status='p', is_public=True).all().order_by('-publish_time')[:10]
        return blogs

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.snippet

Src/apps/blog/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block head %}
<header class="main-header post-head no-cover">
    {% include "widget/main-nav.html" %}
</header>
{% endblock %}
{% block content %}
<main class="content" role="main">
    <article class="post page">


        <section class="post-content">
            <h2 class="post-title">关于作者</h2>
            <p>
            这是Foofish的个人站点, 一直在互联网行业做技术开发相关工作, 对程序语言有一点研究, 对技术架构有一点实践经验, 技术背景包括:
                <ul>
                <li>Python</li>
                <li>Java</li>
                <li>MySQL</li>
                <li>NoSQL</li>
                <li>Unix/Linux</li>
                <li>Web架构</li>
            </ul>
            我的电子邮箱是: lzjun567@gmail.com , <a href="http://weibo.com/lzjun567">微博</a>偶尔用 , 我的<a href="https://github.com/lzjun567">Github</a>干货可能更多点
            </p>

        </section>
        {% include "widget/disqus-comment.html" %}
    </article>
</main>
{% endblock %}
    
 

Src/apps/blog/templates/archive.html
{% extends "base.html" %}
{% load myapp_markup %}
{% block description %}Bloger,Enginner,Python{%endblock%}
{% block head_title %}FooFish的笔录{% endblock %}
{% load staticfiles %}
{% block content %}
{% for blog in blog_list %}
<article class="post post-type-normal" itemscope="" itemtype="http://schema.org/Article">

    <p>
        <time class="post-time" itemprop="dateCreated" datetime="2015-03-23T12:52:58+08:00" content="2015-03-23">
            {{blog.publish_time|date:"Y-m-d" }}
        </time>
        <a href="{{blog.get_absolute_url}}">{{blog.title}}</a></p>


</article>

{% endfor %}

{% if is_paginated %}
<nav class="pager" role="navigation">
    {% if page_obj.has_previous %}
    <a class="newer-posts" href="{% url 'blog:archives' %}?page={{page_obj.previous_page_number}}">上一页 </a>
    {% endif %}
    <span class="page-number">第 {{ page_obj.number }} 页, 共 {{ page_obj.paginator.num_pages }} 页</span>
    {% if page_obj.has_next %}
    <a class="older-posts" href="{% url 'blog:archives' %}?page={{ page_obj.next_page_number }}"> 下一页</a>
    {% endif %}
</nav>
{% endif %}


{% endblock %}

Src/apps/blog/templates/index.html
{% extends "base.html" %}
{% load myapp_markup %}
{% block description %}Bloger,Enginner,Python{%endblock%}
{% block head_title %}FooFish的笔录{% endblock %}
{% load staticfiles %}
{% block content %}
            {% for blog in blog_list %}
            <article>
                <h3><a href="{{blog.get_absolute_url}}">{{blog.title}}</a></h3>


                {% if blog.cover %}
                <img src="{{blog.cover}}" class="img-responsive">
                <br/>
                {% endif %}

                <p> {{blog.content | md1}}</p>
                <p class="text-right">
                    <!--<a href="{{blog.get_absolute_url}}">-->
                        <!--阅读全文...-->
                    <!--</a>-->
                </p>

            </article>
            {% endfor %}

            {% if is_paginated %}
            <nav class="pager" role="navigation">
                {% if page_obj.has_previous %}
                <a class="newer-posts" href="/?page={{page_obj.previous_page_number}}">上一页 </a>
                {% endif %}
                <span class="page-number">第 {{ page_obj.number }} 页, 共 {{ page_obj.paginator.num_pages }} 页</span>
                {% if page_obj.has_next %}
                <a class="older-posts" href="/?page={{ page_obj.next_page_number }}"> 下一页</a>
                {% endif %}
            </nav>
            {% endif %}


{% endblock %}

Src/apps/blog/templates/post_detail.html
{% extends "base.html" %}
{% load myapp_markup %}
{% block description %}{{blog.snippet | truncatewords:50}}{%endblock%}
{% block head_title %}{{blog.title}}{% endblock %}

{% block head_css %}
 <link rel="stylesheet" href="http://apps.bdimg.com/libs/highlight.js/9.1.0/styles/github.min.css">
{% endblock %}

{% load staticfiles %}


{% block content %}

<article class="post">

    <header class="post-header">
        <h1>{{blog.title}}</h1>
        <div class="row">
            <div class="col-sm-6 col-md-6 post-meta">
                <time class="post-date" datetime='{{blog.add_time|date:"b d, Y"}}'>
                    {{blog.add_time|date:"Y-m-d"}}
                </time>
                {% for tag in blog.tags.all %}
                <a href="{%url 'blog:tag' tag%}">{{tag }}</a>
                {% endfor %}
                {% if user.is_authenticated %}
                <a href="{{blog.get_admin_url}}">编辑</a>
                {% endif %}
            </div>

        </div>
    </header>

    {% if blog.cover %}
    <img src="{{blog.cover}}" class="img-responsive">
    <br>
    {% endif %}

    <section class="post-content">
        {{blog.content | md1}}

        <p>原文链接：<a href="{{blog.get_absolute_url}}" rel="author">{{blog.title}}</a>，转载请注明来自<a
                href="http://foofish.net">foofish的博客</a>！
        </p>
    </section>

    <hr>
    <footer>
        <h3>猜你喜欢</h3>
        {% for blog in random_posts %}
        <p><a href="{{blog.get_absolute_url}}" rel="author">{{blog.title}}</a></p>
        {% endfor %}
    </footer>

    {% include "widget/disqus-comment.html" %}
</article>

{% endblock %}

{% block footer_javascript %}

<script src="http://apps.bdimg.com/libs/highlight.js/9.1.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

{% endblock %}

Src/apps/blog/templates/post_list.html
{% extends "base.html" %}
{% block description %}Bloger,Enginner,Python{%endblock%}
{% block head_title %}FooFish的笔录{% endblock %}
{% load staticfiles %}
{% block content %}
            {% for blog in blog_list %}
            <article>
                <h3><a href="{{blog.get_absolute_url}}">{{blog.title}}</a></h3>


                {% if blog.cover %}
                <img src="{{blog.cover}}" class="img-responsive">
                <br/>
                {% endif %}

                <p> {{blog.snippet}}</p>
                <p class="text-right">
                    <a href="{{blog.get_absolute_url}}">
                        阅读全文
                    </a>
                </p>

            </article>
            <hr>
            {% endfor %}

            {% if is_paginated %}
            <nav class="pager" role="navigation">
                {% if page_obj.has_previous %}
                <a class="newer-posts" href="/blog?page={{page_obj.previous_page_number}}">上一页 </a>
                {% endif %}
                <span class="page-number">第 {{ page_obj.number }} 页, 共 {{ page_obj.paginator.num_pages }} 页</span>
                {% if page_obj.has_next %}
                <a class="older-posts" href="/blog?page={{ page_obj.next_page_number }}"> 下一页</a>
                {% endif %}
            </nav>
            {% endif %}


{% endblock %}

Src/apps/blog/templates/tag_list.html
{% extends "base.html" %}
{% load myapp_markup %}
{% block description %}FooFish的念,Bloger,Enginner,Python{%endblock%}
{% block title %}FooFish的笔录{% endblock %}
{%block body_class %} home-template {% endblock %}
{% load staticfiles %}
{% block head %}


<header class="main-header tag-head " style="background-image: url({% static 'img/home-bg.jpg' %})">
    <nav class="main-nav overlay clearfix">
        <a class="blog-logo" href="{%url 'index' %}">Dennis</a>
        <a class="menu-button icon-menu" href="#"><span class="word">Menu</span></a>
    </nav>
    <div class="vertical">
        <div class="main-header-content inner">
            <h1 class="page-title">{{tag_title |default:"Life is Short"}}</h1>
            <h2 class="page-description">
                {{tag_description}}
            </h2>
        </div>
    </div>
</header>


{% endblock %}


{% block content %}
<main id="content" class="content" role="main">
    <div class="main-inner">

        <div id="posts" class="posts-expand">


            <div class="tag-cloud">

                <div class="tag-cloud-tags">

                    {% for tag in tag_list %}
                    <a href="{% url 'blog:tag' tag.title %}" style="font-size:{{tag.font_size}}px; color:{{tag.color}}">{{tag.title}}</a>
                    {% endfor %}

                </div>
            </div>


        </div>


    </div>
</main>


{% endblock %}